# Initiate Study Session

#### This code simulates a user selecting a deck to study. These are the steps needed to prime the deck for today's study. 

- Determine how many cards are due for review
- Determine how many learning cards are due for study
- Determine how many new cards to add to Leitner Box

In [1]:
import pandas as pd
import sqlite3
from datetime import datetime

In [2]:
# Connect to SQLite database (or create it if it doesn't exist)
conn = sqlite3.connect('flashcardsTable.db')

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

## Load Entire Deck into Panda df and Calculate Due Field

In [3]:
# Query the entire table and store it into a pandas DataFrame
df = pd.read_sql_query("SELECT * FROM flashcardsTable", conn)
# Close the connection to the database
conn.close()
df.head(5)

,id,native,target,lastStudied,interval,cardstate
0,1,The reason for which I couldn't attend the mee...,La razón por la cual no pude asistir a la reun...,09/25/2024 01:00:00,5,UNSEEN
1,2,"A few minutes ago, I received an important call.","Hace unos minutos, recibí una llamada importante.",09/25/2024 01:00:00,5,UNSEEN
2,3,A new problem has appeared in the project.,Ha aparecido un nuevo problema en el proyecto.,09/25/2024 01:00:00,5,UNSEEN
3,4,"After finishing the exams, I decided to unleas...","Después de terminar los exámenes, decidí dar r...",09/25/2024 01:00:00,5,UNSEEN
4,5,"After he goes to another office, we will meet.","Después de que vaya a otra oficina, nos reunir...",09/25/2024 01:00:00,5,UNSEEN

In [4]:
# Convert the 'datetime_text' column to datetime type
df['lastdate'] = pd.to_datetime(df['lastStudied'])
# Add a new column that adds the 'minutes' to the 'datetime' column
df['due_datetime'] = df['lastdate'] + pd.to_timedelta(df['interval'], unit='m')
#create new columns of of last studied and due dates, ignoring the hours, minutes, and seconds
df['lastdate_calendar'] = df['lastdate'].dt.date
df['duedate_calendar'] = df['due_datetime'].dt.date
df['weight'] = 0

In [5]:
df.head(5)

,id,native,target,lastStudied,interval,cardstate,lastdate,due_datetime,lastdate_calendar,duedate_calendar,weight
0,1,The reason for which I couldn't attend the mee...,La razón por la cual no pude asistir a la reun...,09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
1,2,"A few minutes ago, I received an important call.","Hace unos minutos, recibí una llamada importante.",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
2,3,A new problem has appeared in the project.,Ha aparecido un nuevo problema en el proyecto.,09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
3,4,"After finishing the exams, I decided to unleas...","Después de terminar los exámenes, decidí dar r...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
4,5,"After he goes to another office, we will meet.","Después de que vaya a otra oficina, nos reunir...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0

## Determine number of cards due for review

These are cards that have been graduated from the learning phase and have also passed their interval. 

REMOVE THIS. AND FORGET ABOUT CARDSTATE GRADUATED. The only states we need are UNSEEN, NEW, and SEEN

In [10]:
# reviewCards = df[(df['cardstate'] == 'GRADUATED') & (df['duedate_calendar'] <= df['lastdate_calendar'])]
# print(len(reviewCards))

## Add NEW Cards to a total of 20

In [41]:
# Step 1: Count how many 'NEW' records there are
new_count = (df['cardstate'] == 'NEW').sum()
print(new_count)

20

In [40]:
# Step 2: If there are fewer than 20 'NEW' records, update some 'UNSEEN' records to 'NEW'
if new_count < 20:
    # Calculate how many 'UNSEEN' need to be converted to 'NEW'
    unseen_to_new = 20 - new_count
    
    # Find the indices of the first 'UNSEEN' records
    unseen_indices = df[df['cardstate'] == 'UNSEEN'].index[:unseen_to_new]
    
    # Update those 'UNSEEN' records to 'NEW'
    df.loc[unseen_indices, 'cardstate'] = 'NEW'

# We should now have exaclty 20 NEW cards. If DB has just been reset, it will be the top 20

In [8]:

df.head(30)

,id,native,target,lastStudied,interval,cardstate,lastdate,due_datetime,lastdate_calendar,duedate_calendar,weight
0,1,The reason for which I couldn't attend the mee...,La razón por la cual no pude asistir a la reun...,09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
1,2,"A few minutes ago, I received an important call.","Hace unos minutos, recibí una llamada importante.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
2,3,A new problem has appeared in the project.,Ha aparecido un nuevo problema en el proyecto.,09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
3,4,"After finishing the exams, I decided to unleas...","Después de terminar los exámenes, decidí dar r...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
4,5,"After he goes to another office, we will meet.","Después de que vaya a otra oficina, nos reunir...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
5,6,"After overcoming his fears, he no longer cared...","Después de superar sus miedos, ya no le import...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
6,7,"After playing, the son's mom will clean Max.","Después de jugar, la mamá del hijo limpiará a ...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
7,8,"After so many issues, I want to get rid of thi...","Después de tantos problemas, quiero quitarme y...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
8,9,"After so much practice, I know it by heart now.","Después de tanto practicar, ahora lo sé de mem...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
9,10,"After the explanation, it's clear to me that w...","Después de la explicación, me queda claro que ...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
10,11,"After the sale, only a few units were left.","Después de la venta, solo quedaban algunas uni...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
11,12,"After trying it several times, he realized it ...","Luego de intentarlo varias veces, se dio cuent...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
12,13,All the students sang in unison during the sch...,Todos los estudiantes cantaron al unísono dura...,09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
13,14,"Already in the early morning, we decided to go...","Ya de madrugada, decidimos irnos a casa.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
14,15,"Although in the background, his contribution w...","Aunque estaba en segundo plano, su contribució...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
15,16,"Although we were already tired, we decided to ...","Aunque ya estábamos cansados, decidimos camina...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
16,17,"Apparently, he won't make it to the meeting on...","Al parecer, no llegará a tiempo para la reunión.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
17,18,"Are you going to quit? No way, I'm not even co...","¿Vas a renunciar? ¡Qué va, ni siquiera lo esto...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
18,19,"As an artist, it's important to make oneself k...","Como artista, es importante darse a conocer en...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
19,20,"As far as I know, the project is going well.","Hasta donde sé, el proyecto va bien.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
20,21,"As for the project, there are some concerns.","En cuanto al proyecto, hay algunas preocupacio...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
21,22,"As I was saying before, the situation is compl...","Como te comentaba antes, la situación es compl...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
22,23,"As part of my routine, I wake up at six every ...","Como parte de mi rutina, me levanto a las seis...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
23,24,"As the day progressed, the heat became more in...","Conforme avanzaba el día, el calor se volvía m...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
24,25,"As the holidays approached, excitement grew in...","Conforme se acercaban las vacaciones, la emoci...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
25,26,"At first, he didn't take the challenge seriously.","Al principio, no se había tomado en serio el d...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
26,27,"At the conference, they also talked about adva...","En la conferencia, se hablaba también de los a...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
27,28,"At the party, there were no shortage of fun mo...","En la fiesta, no faltaron los momentos diverti...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
28,29,"Before answering, he thinks about it for a min...","Antes de responder, él lo piensa durante un mi...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
29,30,"Before going out, make sure to apply sunscreen.","Antes de salir, asegúrate de aplicar bloqueado...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0

# Deck is now ready for study

Due dates and times have been calculated, new cards have been added to the Leitner Box, and we are ready to study. The logic of which cards we study in this session is simple:

- cardstate is NEW, or
- cardstate is SEEN and its due date for review is today

# Update the weights (for weighted random selection) for due cards

In [9]:
# Update 'weight' column for records where 'cardstate' equals 'NEW'
df.loc[df['cardstate'] == 'NEW', 'weight'] = 1

In [10]:
# Today's date in the same format as the `duedate_calendar` column
today = datetime.now().strftime("%Y-%m-%d")

# Update 'weight' for the specified condition
df.loc[
    (df['cardstate'] == 'SEEN') & (df['duedate_calendar'] == today),
    'weight'
] = 10 / df['interval']

In [11]:
df.head(30)

,id,native,target,lastStudied,interval,cardstate,lastdate,due_datetime,lastdate_calendar,duedate_calendar,weight
0,1,The reason for which I couldn't attend the mee...,La razón por la cual no pude asistir a la reun...,09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
1,2,"A few minutes ago, I received an important call.","Hace unos minutos, recibí una llamada importante.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
2,3,A new problem has appeared in the project.,Ha aparecido un nuevo problema en el proyecto.,09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
3,4,"After finishing the exams, I decided to unleas...","Después de terminar los exámenes, decidí dar r...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
4,5,"After he goes to another office, we will meet.","Después de que vaya a otra oficina, nos reunir...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
5,6,"After overcoming his fears, he no longer cared...","Después de superar sus miedos, ya no le import...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
6,7,"After playing, the son's mom will clean Max.","Después de jugar, la mamá del hijo limpiará a ...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
7,8,"After so many issues, I want to get rid of thi...","Después de tantos problemas, quiero quitarme y...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
8,9,"After so much practice, I know it by heart now.","Después de tanto practicar, ahora lo sé de mem...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
9,10,"After the explanation, it's clear to me that w...","Después de la explicación, me queda claro que ...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
10,11,"After the sale, only a few units were left.","Después de la venta, solo quedaban algunas uni...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
11,12,"After trying it several times, he realized it ...","Luego de intentarlo varias veces, se dio cuent...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
12,13,All the students sang in unison during the sch...,Todos los estudiantes cantaron al unísono dura...,09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
13,14,"Already in the early morning, we decided to go...","Ya de madrugada, decidimos irnos a casa.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
14,15,"Although in the background, his contribution w...","Aunque estaba en segundo plano, su contribució...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
15,16,"Although we were already tired, we decided to ...","Aunque ya estábamos cansados, decidimos camina...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
16,17,"Apparently, he won't make it to the meeting on...","Al parecer, no llegará a tiempo para la reunión.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
17,18,"Are you going to quit? No way, I'm not even co...","¿Vas a renunciar? ¡Qué va, ni siquiera lo esto...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
18,19,"As an artist, it's important to make oneself k...","Como artista, es importante darse a conocer en...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
19,20,"As far as I know, the project is going well.","Hasta donde sé, el proyecto va bien.",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1
20,21,"As for the project, there are some concerns.","En cuanto al proyecto, hay algunas preocupacio...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
21,22,"As I was saying before, the situation is compl...","Como te comentaba antes, la situación es compl...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
22,23,"As part of my routine, I wake up at six every ...","Como parte de mi rutina, me levanto a las seis...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
23,24,"As the day progressed, the heat became more in...","Conforme avanzaba el día, el calor se volvía m...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
24,25,"As the holidays approached, excitement grew in...","Conforme se acercaban las vacaciones, la emoci...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
25,26,"At first, he didn't take the challenge seriously.","Al principio, no se había tomado en serio el d...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
26,27,"At the conference, they also talked about adva...","En la conferencia, se hablaba también de los a...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
27,28,"At the party, there were no shortage of fun mo...","En la fiesta, no faltaron los momentos diverti...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
28,29,"Before answering, he thinks about it for a min...","Antes de responder, él lo piensa durante un mi...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0
29,30,"Before going out, make sure to apply sunscreen.","Antes de salir, asegúrate de aplicar bloqueado...",09/25/2024 01:00:00,5,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,0

# Draw a random (weighted) card

You can loop from here down, drawing new cards and rating them

In [12]:
# Today's date
today = datetime.now().strftime("%Y-%m-%d")

# Filter the records that are due today
due_today = df[
    (df['cardstate'] == 'NEW') | 
    ((df['cardstate'] == 'SEEN') & (df['duedate_calendar'] == today))
]

# Select one record weighted by the 'weight' column
if not due_today.empty:
    selected_record = due_today.sample(weights=due_today['weight'], n=1)
    # print(selected_record)
else:
    print("No records are due today.")

In [13]:
selected_record

,id,native,target,lastStudied,interval,cardstate,lastdate,due_datetime,lastdate_calendar,duedate_calendar,weight
5,6,"After overcoming his fears, he no longer cared...","Después de superar sus miedos, ya no le import...",09/25/2024 01:00:00,5,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00,2024-09-25,2024-09-25,1

# Simulate displaying this flashcard to user

In [14]:
print(selected_record['native'])

5    After overcoming his fears, he no longer cared...
Name: native, dtype: object

# Get user's response after flipping the card

## Choices:
1. Got it Wrong
2. Hard
3. Correct
4. Easy

In [15]:
#enter the number for the 
userCardRating = 4

In [16]:
#debugging
print(selected_record['lastStudied'])

5    09/25/2024 01:00:00
Name: lastStudied, dtype: object

# Update card based on user's rating and save update in dataframe

In [35]:
index = selected_record.index[0]  # Get the index of the selected record

match userCardRating:
    case 1:
        #reset interval if user got the card wrong
        df.loc[index, 'interval'] = 5
    case 2:
        #set interval if user rated the card HARD
        df.loc[index, 'interval'] *= 1.2
    case 3:
        #set interval if user rated the card CORRECT
        df.loc[index, 'interval'] *= 1.8
    case 4:
        #set interval if user rated the card CORRECT
        df.loc[index, 'interval'] *= 2.5


df.loc[index, 'cardstate'] = 'SEEN'
#set its last studied time to now
df.loc[index, 'lastStudied'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

In [36]:
# Convert the 'datetime_text' column to datetime type
df['lastdate'] = pd.to_datetime(df['lastStudied'], format='mixed')
# Add a new column that adds the 'minutes' to the 'datetime' column
df['due_datetime'] = df['lastdate'] + pd.to_timedelta(df['interval'], unit='m')
df['lastdate_calendar'] = df['lastdate'].dt.date
df['duedate_calendar'] = df['due_datetime'].dt.date

In [37]:
#debugging
print(df.loc[index, 'lastStudied'])

2024-12-04 13:33:03

In [38]:
df.head(30)

,id,native,target,lastStudied,interval,cardstate,lastdate,due_datetime,lastdate_calendar,duedate_calendar,weight,cardstatus
0,1,The reason for which I couldn't attend the mee...,La razón por la cual no pude asistir a la reun...,09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
1,2,"A few minutes ago, I received an important call.","Hace unos minutos, recibí una llamada importante.",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
2,3,A new problem has appeared in the project.,Ha aparecido un nuevo problema en el proyecto.,09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
3,4,"After finishing the exams, I decided to unleas...","Después de terminar los exámenes, decidí dar r...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
4,5,"After he goes to another office, we will meet.","Después de que vaya a otra oficina, nos reunir...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
5,6,"After overcoming his fears, he no longer cared...","Después de superar sus miedos, ya no le import...",2024-12-04 13:33:03,1220.703125,SEEN,2024-12-04 13:33:03,2024-12-05 09:53:45.187500,2024-12-04,2024-12-05,1,SEEN
6,7,"After playing, the son's mom will clean Max.","Después de jugar, la mamá del hijo limpiará a ...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
7,8,"After so many issues, I want to get rid of thi...","Después de tantos problemas, quiero quitarme y...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
8,9,"After so much practice, I know it by heart now.","Después de tanto practicar, ahora lo sé de mem...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
9,10,"After the explanation, it's clear to me that w...","Después de la explicación, me queda claro que ...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
10,11,"After the sale, only a few units were left.","Después de la venta, solo quedaban algunas uni...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
11,12,"After trying it several times, he realized it ...","Luego de intentarlo varias veces, se dio cuent...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
12,13,All the students sang in unison during the sch...,Todos los estudiantes cantaron al unísono dura...,09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
13,14,"Already in the early morning, we decided to go...","Ya de madrugada, decidimos irnos a casa.",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
14,15,"Although in the background, his contribution w...","Aunque estaba en segundo plano, su contribució...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
15,16,"Although we were already tired, we decided to ...","Aunque ya estábamos cansados, decidimos camina...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
16,17,"Apparently, he won't make it to the meeting on...","Al parecer, no llegará a tiempo para la reunión.",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
17,18,"Are you going to quit? No way, I'm not even co...","¿Vas a renunciar? ¡Qué va, ni siquiera lo esto...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
18,19,"As an artist, it's important to make oneself k...","Como artista, es importante darse a conocer en...",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
19,20,"As far as I know, the project is going well.","Hasta donde sé, el proyecto va bien.",09/25/2024 01:00:00,5.000000,NEW,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,1,NaN
20,21,"As for the project, there are some concerns.","En cuanto al proyecto, hay algunas preocupacio...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
21,22,"As I was saying before, the situation is compl...","Como te comentaba antes, la situación es compl...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
22,23,"As part of my routine, I wake up at six every ...","Como parte de mi rutina, me levanto a las seis...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
23,24,"As the day progressed, the heat became more in...","Conforme avanzaba el día, el calor se volvía m...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
24,25,"As the holidays approached, excitement grew in...","Conforme se acercaban las vacaciones, la emoci...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
25,26,"At first, he didn't take the challenge seriously.","Al principio, no se había tomado en serio el d...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
26,27,"At the conference, they also talked about adva...","En la conferencia, se hablaba también de los a...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
27,28,"At the party, there were no shortage of fun mo...","En la fiesta, no faltaron los momentos diverti...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
28,29,"Before answering, he thinks about it for a min...","Antes de responder, él lo piensa durante un mi...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN
29,30,"Before going out, make sure to apply sunscreen.","Antes de salir, asegúrate de aplicar bloqueado...",09/25/2024 01:00:00,5.000000,UNSEEN,2024-09-25 01:00:00,2024-09-25 01:05:00.000000,2024-09-25,2024-09-25,0,NaN

In [34]:
# Close the connection to the database
conn.close()